mysql:
  host: 1Panel-mysql-RHnT
  port: 3306
  username: freshguard
  password: shlite-01@panel_ps
  database: freshguard
redis:
  host: 1Panel-redis-PDvy
  port: 6379
  password: 6rw332GfSPWW8nBF
  database: 0
sms:
  tencent:
    secret-id: AKID1wjLk7MYcWEiy2yhD1d2DAvSlqpkVM7r
    secret-key:  Qo073mIbkgZGk170qVyUvAC5nYFqJcjf
    sign-name: 青白江游同学工作室
    sdk-app-id: 1400948323
    template-id: 2310769

jwt:
  secret: sj12%hj3sd&jo5pak34h$df7sh#jsd
  exp: 86400
web:
  port: 8080
  context-path: /api